sudo: false

language:
  - php

php:
  - 5.6
  - 7.0

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REF: https://plugins.svn.wordpress.org/wp-cowsay/
  - GH_REF: github.com/kamataryo/wp-cowsay.git

cache:
  yarn: true
  directories:
    - "~/.cache/yarn"

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - curl https://raw.githubusercontent.com/kamataryo/travis-sctipts-collection/master/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - yarn

script:
- phpunit
- npm run generateMo

after_success:
  - openssl aes-256-cbc -K $encrypted_a72eadd36947_key -iv $encrypted_a72eadd36947_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - "./.bin/travis-release.sh"
