sudo: false
dist: trusty

language: php

branches:
  only:
    - master

script:
  - composer install
  - bash .bin/install-wp-tests.sh wordpress_test root '' localhost latest
  - vendor/bin/phpunit
  - ls /tmp/wordpress
  - cat /tmp/wordpress/wp-config.php
