sudo: false

language:
  - php

php:
  - 5.6
  - 7.0

env:
  global:
  - WP_VERSION: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - SVN_REF: https://plugins.svn.wordpress.org/wp-cowsay/
  - GH_REF: kamataryo/wp-cowsay
  - BRANCH_TO_RELEASE: release
  - secure: D5afvjWaEN+Jy+if2uzYdJ+VDlWAZkWm/SHJlN2bkxTHYxinA08urpf4Tvve87XxIIEudF1VhTHavW65yE0q+rmxoAYqJnY5H3QDu9K8hC+nLn9byPAzaR9ouNVpqfVW2GemKMv91QYe5IYTNvjXrHN0amwext5rbi2+W1jp9K52Evw2uNG50VEjMAC9NCU0ydUmHh+gP4C/Fje2S6NTHAfTjQFhscfUWayKt7ymcxWHUf4gqn0uzA/J+jWbSA2YvKO9Kx2J7uVZ4XnR4VvHqzaEGsAhKNrnLwl5gJ5UT+TY6O1eFdlU1gmuN75FrEW9pajqQ6cN0H8mBoAcJYE09lwDryEhXIZaDaEndzSD2aEa2mhawj4X+YOEhG3tEjswebDghP1viVJh+MVBKXD1zuuxV+F1x4fjB9Mfx/Zt58L96/P7wFFPHzIl87MzWZswdWIc+rMhBrxZgJ7nE9BeSXoJIhnYF3mVKt2tZawlWKKB4WSMH8M3wfybb2cgeNRSC9Mzc0abnOHu97bVq0F1eQ1QqTLUpCNogizoOTJsQ/nyE40YkqKLw1MXuy4svxhb+CVPpnYR/hmQ6dRjWCRXmw+no6kqkInqrF1Z1J4qbnJ7q/JVEJi4++uSG9GN7DZZU0WyX1YzkNYfW+q9btPQ5VEnnbs29PZZsOLqO/EjkmE=

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - curl https://raw.githubusercontent.com/kamataryo/travis-sctipts-collection/master/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - npm install

script:
- phpunit
- npm run generateMo

after_success:
  - openssl aes-256-cbc -K $encrypted_a72eadd36947_key -iv $encrypted_a72eadd36947_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - "./.bin/travis-release.sh"
