sudo: false
dist: trusty

language: php

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer install
  - bash .bin/install-wp-tests.sh wordpress_test root '' localhost latest
  - vendor/bin/phpunit
