sudo: false

language:
  - php

php:
  - 5.6
  - 7.0

cache:
  yarn: true
  directories:
  - "~/.cache/yarn"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
  - curl https://raw.githubusercontent.com/kamataryo/travis-sctipts-collection/master/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - yarn
  - npm run generateMo

script:
- phpunit

#after_success:
# - curl https://raw.githubusercontent.com/kamataryo/travis-sctipts-collection/master/deploy-wp-plugin.sh | bash

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REF: https://plugins.svn.wordpress.org/wp-cowsay/
  - GH_REF: github.com/kamataryo/wp-cowsay.git
