sudo: false

language:
  - php

php:
  - 7.0

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - bash ./.bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - npm install

script:
- phpunit
- npm run generateMo
