sudo: false

language:
  - php

php:
  - 5.6
  - 7.0

env:
  global:
  - WP_VERSION: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - SVN_REF: https://plugins.svn.wordpress.org/wp-cowsay/
  - GH_REF: kamataryo/wp-cowsay
  - BRANCH_TO_RELEASE: release
  - secure: ZAgsckrT09kOsWMP5BUV2XOq2sdSMpfTkIUQLo0yOA9MYGZRvHYKyOPffhLDtTXfYATOOXQpNYRMP7+P/jHy0TcEVASRyyuCf4ET/wceKm2ZgJvio7z83BH+UKrY5NzK6p7zmzGiu138vgmFoYbTgNE2nPNwHE2cQpVN/xQtC7sTWZ2q7cEKBL9NtMj3/cgYL/SiYmAm7+hlFYSghcGimA9f0zqK5KskvcpC7Pys6I0O/TnZcULB7qOLqPGtD+MxTpEKPCYfrNWkQfvlNk1F9H+ISzomkZ1lQisCX/OxdrmIDaH80L+St7nIQSpxJ5+xpGIkyE0rKQk3bA2Ig2ozt86XEycfma2VawdGN/M7sgPxU7Fxo2EvRh2F56MwkQzEr6OoPbfl6PWlH5ZEVch4wnBey32OXNg/nuY0CxTXSiP72b1RK4lGajMqSfb/sE5aBdubJHVnhNNFHsZKHvVRx19pFMSRgH7cIkrk6Z5qymoN8Yn0tq9cfghNlm4joevYmek+6DWk7MwI0fnSt0DkuLJX5hxNnx9HQYJR90u9Blle8nxMD3TOnetLwn39eSXLj1My7PHK8NI4LJ11NbaOwelVIvH5dcbgCIn3R1dCaFdqzXYqWeX7HHtCrorz3sQU66vybiGXRhkW4LYKsMfHH9n/w5PxjVZJwCnfU5J9njo=

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - curl https://raw.githubusercontent.com/kamataryo/travis-sctipts-collection/master/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - npm install

script:
- phpunit
- npm run generateMo

after_success:
  - openssl aes-256-cbc -K $encrypted_a72eadd36947_key -iv $encrypted_a72eadd36947_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - "./.bin/travis-release.sh"
