version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2-cli-node
    - image: circleci/mysql:5.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install mysql-client subversion-tools
      - run: sudo docker-php-ext-install mysqli
      - run: composer install
      - run: npm inastall
      - run: npm run generateMo
      - run: bash .bin/install-wp-tests.sh wordpress_test root '' '127.0.0.1' latest
      - run: vendor/bin/phpunit
      - run: composer install --no-dev

      - persist_to_workspace:
          root: .
          paths:
              - .

  deploy:
    docker:
    - image: circleci/php:7.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: sudo apt-get install subversion-tools
      - run: .bin/circle-release.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
