version: 2
jobs:
  test:
    docker:
    - image: wordpress:cli-php-7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install
      - run: npm install
      - run: phpunit
      - run: npm run generateMo

      - persist_to_workspace:
          root: .
          paths:
              - .

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ./.bin/circle-release.sh
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
