version: 2
jobs:
  test:
    docker:
    - image: circleci/php:7.2

    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install mysql-client subversion-tools
      - run: sudo docker-php-ext-install mysqli
      - run: composer install
      - run: bash ./.bin/install-wp-tests.sh wordpress_test root '' localhost 5.1.1
      - run: vendor/bin/phpunit

      - persist_to_workspace:
          root: .
          paths:
              - .

  deploy:
    docker:
      - image: wordpress:5.1.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: ./.bin/circle-release.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
